#!/usr/bin/env python3
###############################################################################
# Copyright 2015-2016 University of Florida. All rights reserved.
# This file is part of UF CTS-IT's NACCulator project.
# Use of this source code is governed by the license found in the LICENSE file.
###############################################################################

from nacc.uds3 import blanks
from nacc.uds3 import clsform
import forms as ivp_forms
from nacc.uds3 import packet as ivp_packet
import sys


def build_lbd_ivp_form(record):
    # Converts REDCap CSV data into a packet (list of IVP Form objects)
    packet = ivp_packet.Packet()

    # Set up the forms..........
    # Not sure if NACCulator is case sensitive or not. The variables 
    # are all lowercase on the REDCap DED.
    B1L = ivp_forms.FormB1L()
    B1L.LBSSALIV = record['LBSSALIV']
    B1L.LBSSWALL = record['BSSWALL']
    B1L.LBSINSeX = record['LBSINSeX']
    B1L.LBSPrSeX = record['LBSPrSeX']
    B1L.LBSWeIGH = record['LBSWeIGH']
    B1L.LBSSMeLL = record['LBSSMeLL']
    B1L.LBSSWeAt = record['LBSSWeAT']
    B1L.LBStoLCD = record['LBStoLCD']
    B1L.LBStoLHt = record['LBStoHLt']
    B1L.LBSDBVIS = record['LBSDBVIS']
    B1L.LBSCoNSt = record['LBSCoNST']
    B1L.LBSHDStL = record['LBSHDStL']
    B1L.LBSLSStL = record['LBSLSStL']
    B1L.LBSUBLAD = record['LBSUBLAD']
    B1L.LBSUStrM = record['LBSUStrM']
    B1L.LBSUPASS = record['LBSUPASS']
    B1L.LBSDZStU = record['LBSDZStU']
    B1L.LBSDZStN = record['LBSDZStN']
    B1L.LBSFAINt = record['LBSFAINt']
    B1L.LBSPSyM  = record['LBSPSyM']
    B1L.LBPSyAGe = record['LBPSyAGe']
    B1L.LBSSUPSy = record['LBSSUPSy']
    B1L.LBSSUPDI = record['LBSSUPDI']
    B1L.LBSSUPHt = record['LBSSUPHt']
    B1L.LBSStNSy = record['LBSStNSy']
    B1L.LBSStNDI = record['LBSStNDI']
    B1L.LBSStNHt = record['LBSStNHt']
    B1L.LBSAGerM = record['LBSAGerM']
    B1L.LBSAGeSM = record['LBSAGeSM']
    B1L.LBSAGeGt = record['LBSAGeGt']
    B1L.LBSAGeFL = record['LBSAGeFL']
    B1L.LBSAGetr = record['LBSAGetr']
    B1L.LBSAGeBr = record['LBSAGeBr']
    B1L.LBSSCLAU = record['LBSSCLAU']
    B1L.LBSSCLVr = record['LBSSCLVr']
    B1L.LBSSCLot = record['LBSSCLot']
    B1L.LBSSCor = record['LBSSCor']
    packet.append(B1L)

    B2L = ivp_forms.FormB2L()
    B2L.LBUDSPCH = record['LBUDSPCH']
    B2L.LBUDSALV = record['LBUDSALV']
    B2L.LBUDSWAL = record['LBUDSWAL']
    B2L.LBUWrIte = record['LBUWrIte']
    B2L.LBUDFooD = record['LBUDFooD']
    B2L.LBUDreSS = record['LBUDreSS']
    B2L.LBUDHyGN = record['LBUDHyGN']
    B2L.LBUDtUrN = record['LBUDtUrN']
    B2L.LBUDFALL = record['LBUDFALL']
    B2L.LBUDFrZ  = record['LBUDFrZ']
    B2L.LBUDWALK = record['LBUDWALK']
    B2L.LBUDtreM = record['LBUDtreM']
    B2L.LBUDSeNS = record['LBUDSeNS']
    packet.append(B2L)

    B3L = ivp_forms.FormB3L()
    B3L.LBUMSPCH = record['LBUMSPCH']
    B3L.LBUMSPCX = record['LBUMSPCX']
    B3L.LBUMFACe = record['LBUMFACe']
    B3L.LBUMFACX = record['LBUMFACX']
    B3L.LBUMtrFA = record['LBUMtrFA']
    B3L.LBUtrFAX = record['LBUtrFAX']
    B3L.LBUMtrrH = record['LBUMtrrH']
    B3L.LBUtrrHX = record['LBUtrrHX']
    B3L.LBUMtrLH = record['LBUMtrLH']
    B3L.LBUtrLHX = record['LBUtrLHX']
    B3L.LBUMtrrF = record['LBUMtrrF']
    B3L.LBUtrrFX = record['LBUtrrFX']
    B3L.LBUMtrLF = record['LBUMtrLF']
    B3L.LBUtrLFX = record['LBUtrLFX']
    B3L.LBUMAtrH = record['LBUMAtrH']
    B3L.LBUAtrHX = record['LBUAtrHX']
    B3L.LBUMAtLH = record['LBUMAtLH']
    B3L.LBUAtLHX = record['LBUAtLHX']
    B3L.LBUMrGNK = record['LBUMrGNK']
    B3L.LBUrGNKX = record['LBUrGNKX']
    B3L.LBUMrGrU = record['LBUMrGrU']
    B3L.LBUrGrUX = record['LBUrGrUX']
    B3L.LBUMrGLU = record['LBUMrGLU']
    B3L.LBUrGLUX = record['LBUrGLUX']
    B3L.LBUMrGrL = record['LBUMrGrL']
    B3L.LBUrGrLX = record['LBUrGrLX']
    B3L.LBUMrGLL = record['LBUMrGLL']
    B3L.LBUrGLLX = record['LBUrGLLX']
    B3L.LBUMFtrH = record['LBUMFtrH']
    B3L.LBUFtrHX = record['LBUFtrHX']
    B3L.LBUMFtLH = record['LBUMFtLH']
    B3L.LBUFtLHX = record['LBUFtLHX']
    B3L.LBUMHMrH = record['LBUMHMrH']
    B3L.LBUHMrHX = record['LBUHMrHX']
    B3L.LBUMHMLH = record['LBUMHMLH']
    B3L.LBUHMLHX = record['LBUHMLHX']
    B3L.LBUMPSrH = record['LBUMPSrH']
    B3L.LBUPSrHX = record['LBUPSrHX']
    B3L.LBUMPSLH = record['LBUMPSLH']
    B3L.LBUPSLHX = record['LBUPSLHX']
    B3L.LBUMLGrL = record['LBUMLGrL']
    B3L.LBULGrLX = record['LBULGrLX']
    B3L.LBUMLGLL = record['LBUMLGLL']
    B3L.LBULGLLX = record['LBULGLLX']
    B3L.LBUMrISe = record['LBUMrISe']
    B3L.LBUMrISX = record['LBUMrISX']
    B3L.LBUMPoSt = record['LBUMPoSt']
    B3L.LBUMPoSX = record['LBUMPoSX']
    B3L.LBUMGAIt = record['LBUMGAIt']
    B3L.LBUMGAIX = record['LBUMGAIX']
    B3L.LBUPStBL = record['LBUPStBL']
    B3L.LBUPStBX = record['LBUPStBX']
    B3L.LBUMBrAD = record['LBUMBrAD']
    B3L.LBUMBrAX = record['LBUMBrAX']
    B3L.LBUMHNyr = record['LBUMHNyr']
    B3L.LBUMHNyX = record['LBUMHNyX']
    packet.append(B3L)

    B4L = ivp_forms.FormB4L()
    B4L.LBDeLUS  = record['LBDeLUS']    
    B4L.LBDHUrt  = record['LBDHUrt']    
    B4L.LBDSteAL = record['LBDSteAL']
    B4L.LBDAFFr  = record['LBDAFFr']    
    B4L.LBDGUeSt = record['LBDGUeSt']
    B4L.LBDIMPoS = record['LBDIMPoS']
    B4L.LBDHoMe  = record['LBDHoMe']    
    B4L.LBDABAND = record['LBDABAND']
    B4L.LBDPreS  = record['LBDPreS']
    B4L.LBDotHer = record['LBDotHer']
    B4L.LBDeLFrQ = record['LBDeLFrQ']
    B4L.LBDeLSeV = record['LBDeLSeV']
    B4L.LBDeLDSt = record['LBDeLDSt']
    B4L.LBHALL   = record['LBHALL']
    B4L.LBHVoICe = record['LBHVoICe']
    B4L.LBHPeoPL = record['LBHPeoPL']
    B4L.LBHNotPr = record['LBHNotPr']
    B4L.LBHoDor  = record['LBHoDor']
    B4L.LBHFeeL  = record['LBHFeeL']
    B4L.LBHtASte = record['LBHtASte']
    B4L.LBHotSeN = record['LBHotSeN']
    B4L.LBHALFrQ = record['LBHALFrQ']
    B4L.LBHALSeV = record['LBHALSeV']
    B4L.LBHALDSt = record['LBHALDSt']
    B4L.LBANXIet = record['LBANXIet']
    B4L.LBANeVNt = record['LBANeVNt']
    B4L.LBANreLX = record['LBANreLX']
    B4L.LBANBrtH = record['LBANBrtH']
    B4L.LBANBUtt = record['LBANBUtt']
    B4L.LBANPLAC = record['LBANPLAC']
    B4L.LBANSePr = record['LBANSePr']
    B4L.LBANotHr = record['LBANotHr']
    B4L.LBANXFrQ = record['LBANXFrQ']
    B4L.LBANXSeV = record['LBANXSeV']
    B4L.LBANXDSt = record['LBANXDSt']
    B4L.LBAPAtHy = record['LBAPAtHy']
    B4L.LBAPSPNt = record['LBAPSPNt']
    B4L.LBAPCoNV = record['LBAPCoNV']
    B4L.LBAPAFF  = record['LBAPAFF']
    B4L.LBAPCHor = record['LBAPCHor']
    B4L.LBAPINt  = record['LBAPINt']
    B4L.LBAPFAML = record['LBAPFAML']
    B4L.LBAPINtr = record['LBAPINtr']
    B4L.LBAPotH  = record['LBAPotH']
    B4L.LBAPAFrQ = record['LBAPAFrQ']
    B4L.LBAPASeV = record['LBAPASeV']
    B4L.LBAPADSt = record['LBAPADSt']
    B4L.LBDoPAM  = record['LBDoPAM']
    B4L.LBDAGe   = record['LBDAGe']
    B4L.LBDDrUG1 = record['LBDDrUG1']
    B4L.LBDDoSe1 = record['LBDDoSe1']
    B4L.LBDAGe2  = record['LBDAGe2']
    B4L.LBDDrUG2 = record['LBDDrUG2']
    B4L.LBDDoSe2 = record['LBDDoSe2']
    B4L.LBDeLAGe = record['LBDeLAGe']
    B4L.LBDeLMeD = record['LBDeLMeD']
    B4L.LBDeLMD1 = record['LBDeLMD1']
    B4L.LBDeLMD2 = record['LBDeLMD2']
    B4L.LBHALAGe = record['LBHALAGe']
    B4L.LBHALMeD = record['LBHALMeD']
    B4L.LBHALMD1 = record['LBHALMD1']
    B4L.LBHALMD2 = record['LBHALMD2']
    B4L.LBANXAGe = record['LBANXAGe']
    B4L.LBANXMeD = record['LBANXMeD']
    B4L.LBANXMD1 = record['LBANXMD1']
    B4L.LBANXMD2 = record['LBANXMD2']
    B4L.LBAPAAGe = record['LBAPAAGe']
    B4L.LBAPAMeD = record['LBAPAMeD']
    B4L.LBAPAMD1 = record['LBAPAMD1']
    B4L.LBAPAMD2 = record['LBAPAMD2']
    packet.append(B4L)

    B5L = ivp_forms.FormB5L()
    B5L.LBMLtHrG = record['LBMLtHrG']
    B5L.LBMSLeeP = record['LBMSLeeP']
    B5L.LBMDISrG = record['LBMDISrG']
    B5L.LBMStAre = record['LBMStAre']
    packet.append(B5L)

    B6L = ivp_forms.FormB6L()
    B6L.LBSPCGIM = record['LBSPCGIM']
    B6L.LBSPDrM  = record['LBSPDrM']
    B6L.LBSPyrS  = record['LBSPyrS']
    B6L.LBSPMoS  = record['LBSPMoS']
    B6L.LBSPINJS = record['LBSPINJS']
    B6L.LBSPINJP = record['LBSPINJP']
    B6L.LBSPCHAS = record['LBSPCHAS']
    B6L.LBSPMoVe = record['LBSPMoVe']
    B6L.LBSPLeGS = record['LBSPLeGS']
    B6L.LBSPNerV = record['LBSPNerv']
    B6L.LBSPUrGL = record['LBSPUrGL']
    B6L.LBSPSeNS = record['LBSPSeNS']
    B6L.LBSPWorS = record['LBSPWorS']
    B6L.LBSPWALK = record['LBSPWALK']
    B6L.LBSPAWAK = record['LBSPAWAK']
    B6L.LBSPBrtH = record['LBSPBrtH']
    B6L.LBSPtrt  = record['LBSPtrt']
    B6L.LBSPCrMP = record['LBSPCrMP']
    B6L.LBSPALrt = record['LBSPALrt']
    packet.append(B6L)

    B7L = ivp_forms.FormB7L()
    B7L.LBSCLIV  = record['LBSCLIV']    
    B7L.LBSCSLP  = record['LBSCSLP']
    B7L.LBSCBeHV = record['LBSCBeHV']
    B7L.LBSCDrM  = record['LBSCDrM']
    B7L.LBSCyrS  = record['LBSCyrS']
    B7L.LBSCMoS  = record['LBSCMoS']
    B7L.LBSCINJS = record['LBSCINJS']
    B7L.LBSCINJP = record['LBSCINJP']
    B7L.LBSCCHAS = record['LBSCCHAS']
    B7L.LBSCMoVe = record['LBSCMoVe']
    B7L.LBSCLeGS = record['LBSCLeGS']
    B7L.LBSCNerV = record['LBSCNerV']
    B7L.LBSCSeNS = record['LBSCSeNS']
    B7L.LBSCWorS = record['LBSCWorS']
    B7L.LBSCWALK = record['LBSCWALK']
    B7L.LBSCAWAK = record['LBSCAWAK']
    B7L.LBSCBrtH = record['LBSCBrtH']
    B7L.LBSCtrt  = record['LBSCtrt']
    B7L.LBSCCrMP = record['LBSCCrMP']
    B7L.LBSCALrt = record['LBSCALrt']
    packet.append(B7L)

    B8L = ivp_forms.FormB8L()
    B8L.PACoGIMP = record['PACoGIMP']
    B8L.PANSFALL = record['PANSFALL']
    B8L.PANSWKoF = record['PANSWKoF']
    B8L.PANSLyAW = record['PANSLyAW']
    B8L.PANSWKer = record['PANSWKer']
    B8L.PANSLttL = record['PANSLttL']
    B8L.SCPArAte = record['SCPArAte']
    B8L.PADSUNeX = record['PADSUNeX']
    B8L.PADSSItP = record['PADSSItP']
    B8L.PADSWAtV = record['PADSWAtV']
    B8L.PADStALK = record['PADStALK']
    B8L.PADSAWDy = record['PADSAWDy']
    B8L.PADSFLDy = record['PADSFLDy']
    packet.append(B8L)

    B9L = ivp_forms.FormB9L()
    B9L.CoNSFALL = record['CoNSFALL']
    B9L.CoNSWKoF = record['CoNSWKoF']
    B9L.CoNSLyAW = record['CoNSLyAW']
    B9L.CoNSWKer = record['CoNSWKer']
    B9L.CoNSLttL = record['CoNSLttL']
    B9L.SCCorAte = record['SCCorAte']
    B9L.CoDSUNeX = record['CoDSUNeX']
    B9L.CoDSSItP = record['CoDSSItP']
    B9L.CoDSWAtV = record['CoDSWAtV']
    B9L.CoDStALK = record['CoDStALK']
    B9L.CoDSAWDy = record['CoDSAWDy']
    B9L.CoDSFLDy = record['CoDSFLDy']
    B9L.SCCoFrSt = record['SCCoFrSt']
    B9L.SCCoAGeN = record['SCCoAGeN']
    B9L.SCCoAGeD = record['SCCoAGeD']
    B9L.SCCoCoMP = record['SCCoCoMP']
    B9L.SCCoSCVr = record['SCCoSCVr']
    B9L.SCCootH  = record['SCCootH']
    B9L.SCCoSCor = record['SCCoSCor']
    packet.append(B9L)

    C1L = ivp_forms.FormC1L()
    C1L.LBNSWorD = record['LBNSWorD']
    C1L.LBNSCoLr = record['LBNSCoLr']
    C1L.LBNSCLWD = record['LBNSCLWD']
    C1L.LBNPFACe = record['LBNPFACe']
    C1L.LBNPNoIS = record['LBNPNoIS']
    C1L.LBNPtCor = record['LBNPtCor']
    C1L.LBNPPArD = record['LBNPPArD']
    packet.append(C1L)

    D1L = ivp_forms.FormD1L()
    D1L.LBCDSCoG = record['LBCDSCoG']
    D1L.LBCCMeM  = record['LBCCMeM']
    D1L.LBCCLANG = record['LBCCLANG']
    D1L.LBCCAtt  = record['LBCCAtt']
    D1L.LBCCeXDe = record['LBCCeXDe']
    D1L.LBCCVIS  = record['LBCCVIS']
    D1L.LBCDSMoV = record['LBCDSMoV']
    D1L.LBCMBrAD = record['LBCMBrAD']
    D1L.LBCMrIGD = record['LBCMrIGD']
    D1L.LBCMrtrM = record['LBCMrtrM']
    D1L.LBCMPtrM = record['LBCMPtrM']
    D1L.LBCMAtrM = record['LBCMAtrM']
    D1L.LBCMMyoC = record['LBCMMyoC']
    D1L.LBCMGAIt = record['LBCMGAIt']
    D1L.LBCMPINS = record['LBCMPINS']
    D1L.LBCDSBeV = record['LBCDSBeV']
    D1L.LBCBDeP  = record['LBCBDeP']
    D1L.LBCBAPA  = record['LBCBAPA']
    D1L.LBCBANX  = record['LBCBANX']
    D1L.LBCBHALL = record['LBCBHALL']
    D1L.LBCBDeL  = record['LBCBDeL'] 
    D1L.LBCDSAUt = record['LBCDSAUt']
    D1L.LBCAreM  = record['LBCAreM']
    D1L.LBCAAPN  = record['LBCAAPN']
    D1L.LBCALGSL = record['LBCALGSL']
    D1L.LBCArSLe = record['LBCArSLe']
    D1L.LBCADtSL = record['LBCADtSL']
    D1L.LBCACGFL = record['LBCACGFL']
    D1L.LBCAHyPt = record['LBCAHyPt']
    D1L.LBCACoNS = record['LBCACoNS']
    D1L.LBCAHyPS = record['LBCAHyPS']
    D1L.LBCAFALL = record['LBCAFALL']
    D1L.LBCASyNC = record['LBCASyNC']
    D1L.LBCASNAP = record['LBCASNAP']
    D1L.LBCoGSt  = record['LBCoGSt']
    D1L.LBCoGDX  = record['LBCoGDX']
    packet.append(D1L)
    
    E1L = ivp_forms.FormE1L()
    E1L.LBGLrrK2 = record['LBGLrrK2']
    E1L.LBGLrKIS = record['LBGLrKIS']
    E1L.LBGPArK2 = record['LBGPArK2']
    E1L.LBGPK2IS = record['LBGPK2IS']
    E1L.LBGPArK7 = record['LBGPArK7']
    E1L.LBGPK7IS = record['LBGPK7IS']
    E1L.LBGPINK1 = record['LBGPINK1']
    E1L.LBGPNKIS = record['LBGPNKIS']
    E1L.LBGSNCA  = record['LBGSNCA']
    E1L.LBGSNCIS = record['LBGSNCIS']
    E1L.LBGGBA   = record['LBGGBA']
    E1L.LBGGBAIS = record['LBGGBAIS']
    E1L.LBGotHr  = record['LBGotHr']
    E1L.LBGotHIS = record['LBGotHIS']
    E1L.LBGotHX  = record['LBGotHX']
    packet.append(E1L)

    E2L = ivp_forms.FormE2L()
    E2L.LBISMrI  = record['LBISMrI']    
    E2L.LBISMMo  = record['LBISMMo']
    E2L.LBISMDy  = record['LBISMDy']
    E2L.LBISMyr  = record['LBISMyr']
    E2L.LBISMQAV = record['LBISMQAV']
    E2L.LBISMHIP = record['LBISMHIP']
    E2L.LBISMAVL = record['LBISMAVL']
    E2L.LBISMDCM = record['LBISMDCM']
    E2L.LBISMFMt = record['LBISMFMt']
    E2L.LBISMADN = record['LBISMADN']
    E2L.LBISMVer = record['LBISMVer']
    E2L.LBISMMAN = record['LBISMMAN']
    E2L.LBISMoM  = record['LBISMoM']
    E2L.LBISMStr = record['LBISMStr']
    E2L.LBISMoS  = record['LBISMoS']
    E2L.LBIFPet  = record['LBIFPet']
    E2L.LBIFPMo  = record['LBIFPMo']
    E2L.LBIFPDy  = record['LBIFPDy']
    E2L.LBIFPyr  = record['LBIFPyr']
    E2L.LBIFPQAV = record['LBIFPQAV']
    E2L.LBIFPoCC = record['LBIFPoCC']
    E2L.LBIFPtPP = record['LBIFPtPP']
    E2L.LBIFPISL = record['LBIFPISL']
    E2L.LBIFPAVL = record['LBIFPAVL']
    E2L.LBIFPDCM = record['LBIFPDCM']
    E2L.LBIFPFMt = record['LBIFPFMt']
    E2L.LBIFPADN = record['LBIFPADN']
    E2L.LBIFPVer = record['LBIFPVer']
    E2L.LBIFPMAN = record['LBIFPMAN']
    E2L.LBIFPoM  = record['LBIFPoM']
    E2L.LBIAPet  = record['LBIAPet']
    E2L.LBIAPMo  = record['LBIAPMo']
    E2L.LBIAPDy  = record['LBIAPDy']
    E2L.LBIAPyr  = record['LBIAPyr']
    E2L.LBIAPQAV = record['LBIAPQAV']
    E2L.LBIAPAVL = record['LBIAPAVL']
    E2L.LBIAPDCM = record['LBIAPDCM']
    E2L.LBIAPFMt = record['LBIAPFMt']
    E2L.LBIAPLIG = record['LBIAPLIG']
    E2L.LBIAPoL  = record['LBIAPoL']
    E2L.LBIAPADN = record['LBIAPADN']
    E2L.LBIAPVer = record['LBIAPVer']
    E2L.LBIAPMAN = record['LBIAPMAN']
    E2L.LBIAPoM  = record['LBIAPoM']
    E2L.LBItPet  = record['LBItPet']
    E2L.LBItPMo  = record['LBItPMo']
    E2L.LBItPDy  = record['LBItPDy']
    E2L.LBItPyr  = record['LBItPyr']
    E2L.LBItPQAV = record['LBItPQAV']
    E2L.LBItPAVL = record['LBItPAVL']
    E2L.LBItPDCM = record['LBItPDCM']
    E2L.LBItPFMt = record['LBItPFMt']
    E2L.LBItPLIG = record['LBItPLIG']
    E2L.LBItPoL  = record['LBItPoL']
    E2L.LBItPADN = record['LBItPADN']
    E2L.LBItPVer = record['LBItPVer']
    E2L.LBItPMAN = record['LBItPMAN']
    E2L.LBItPoM  = record['LBItPoM']
    E2L.LBIDAtS  = record['LBIDAtS']
    E2L.LBIDSMo  = record['LBIDSMo']
    E2L.LBIDSDy  = record['LBIDSDy']
    E2L.LBIDSyr  = record['LBIDSyr']
    E2L.LBIDSQAV = record['LBIDSQAV']
    E2L.LBIDSABN = record['LBIDSABN']
    packet.append(E2L)

    E3L = ivp_forms.FormE3L()
    E3L.LBoPoLyS = record['LBoPoLyS']
    E3L.LBoPoSMo = record['LBoPoSMo']
    E3L.LBoPoSDy = record['LBoPoSDy']
    E3L.LBoPoSyr = record['LBoPoSyr']
    E3L.LBoPoPoS = record['LBoPoPoS']
    E3L.LBoPoAVL = record['LBoPoAVL']
    E3L.LBoCMIBG = record['LBoCMIBG']
    E3L.LBoCMMo  = record['LBoCMMo']
    E3L.LBoCMDy  = record['LBoCMDy']
    E3L.LBoCMyr  = record['LBoCMyr']
    E3L.LBoCMPoS = record['LBoCMPoS']
    E3L.LBoCMAVL = record['LBoCMAVL']
    E3L.LBoANoS  = record['LBoANoS']
    E3L.LBoANMo  = record['LBoANMo']
    E3L.LBoANDy  = record['LBoANDy']
    E3L.LBoANyr  = record['LBoANyr']
    E3L.LBoANPoS = record['LBoANPoS']
    E3L.LBoANAVL = record['LBoANAVL']
    E3L.LBoANVer = record['LBoANVer']
    E3L.LBoANotH = record['LBoANotH']
    E3L.LBoeeG   = record['LBOeeG']
    E3L.LBoeGMo  = record['LBoeGMo']
    E3L.LBoeGDy  = record['LBoeGDy']
    E3L.LBoeGyr  = record['LBoeGyr']
    E3L.LBoeGPoS = record['LBoeGPoS']
    E3L.LBoeGAVL = record['LBoeGAVL']
    E3L.LBoMSLt  = record['LBoMSLt']
    E3L.LBoMSMo  = record['LBoMSMo']
    E3L.LBoMSDy  = record['LBoMSDy']
    E3L.LBoMSyr  = record['LBoMSyr']
    E3L.LBoMSPoS = record['LBoMSPoS']
    E3L.LBoMSAVL = record['LBoMSAVL']
    E3L.LBotILt  = record['LBotILt']
    E3L.LBotLMo  = record['LBotLMo']
    E3L.LBotLDy  = record['LBotLDY']
    E3L.LBotLyr  = record['LBotLyr']
    E3L.LBotLPoS = record['LBoPoS']
    E3L.LBotLAVL = record['LBoAVL']
    E3L.LBoQSArt = record['LBoQSArt']
    E3L.LBoQSMo  = record['LBoQSMo']
    E3L.LBoQSDy  = record['LBoQSDy']
    E3L.LBoQSyr  = record['LBoQSyr']
    E3L.LBoQSPoS = record['LBoQSPoS']
    E3L.LBoSGAVL = record['LBoSGAVL']
    E3L.LBotHerM = record['LBotHerM']
    E3L.LBotHMo  = record['LBotHMo']
    E3L.LBotHDy  = record['LBotHDy']
    E3L.LBotHyr  = record['LBotHyr']
    E3L.LBotHPoS = record['LBotHPoS']
    E3L.LBotHAVL = record['LBotHAVL']
    E3L.LBoCGAIt = record['LBoCGAIt']
    E3L.LBoCGMo  = record['LBoCGMo']
    E3L.LBoCGDy  = record['LBoCGDy']
    E3L.LBoCGyr  = record['LBoCGyr']
    E3L.LBoCGPoS = record['LBoCGPoS']
    E3L.LBoCGAVL = record['LBoCGAVL']
    packet.append(E3L)


# update_header takes the header form to fill out info about the full packet, 
# but i'm not sure what this if/else thing does

# def update_header(record, packet):
#     for header in packet:
#         header.PACKET = "I"
#         header.FORMID = header.form_name
#         if header.FORMID.value == "B5 ":
#             header.FORMVER = "3.1"
#         elif header.FORMID.value == "C1S":
#             header.FORMVER = 2
#         else:
#             header.FORMVER = 3
#         header.ADCID = record['adcid']
#         header.PTID = record['ptid']
#         header.VISITMO = record['visitmo']
#         header.VISITDAY = record['visitday']
#         header.VISITYR = record['visityr']
#         header.VISITNUM = record['visitnum']
#         header.INITIALS = record['initials']
