#!/usr/bin/env python3
###############################################################################
# Copyright 2015-2016 University of Florida. All rights reserved.
# This file is part of UF CTS-IT's NACCulator project.
# Use of this source code is governed by the license found in the LICENSE file.
###############################################################################

from nacc.uds3 import blanks
from nacc.uds3 import clsform
from . import forms as lbd_fvp_forms
# import forms as lbd_fvp_forms
from nacc.uds3 import packet as lbd_fvp_packet
import sys
import re


def build_uds3_lbd_fvp_form(record):
    # Converts REDCap CSV data into a packet (list of FVP Form objects)
    packet = lbd_fvp_packet.Packet()

    # Set up the forms..........
    # Not sure if NACCulator is case sensitive or not. The variables 
    # are all lowercase on the REDCap DED.
    B1L = lbd_fvp_forms.FormB1L()
    B1L.LBSSALIV = record['fu_LBSSALIV']
    B1L.LBSSWALL = record['fu_BSSWALL']
    B1L.LBSINSeX = record['fu_LBSINSeX']
    B1L.LBSPrSeX = record['fu_LBSPrSeX']
    B1L.LBSWeIGH = record['fu_LBSWeIGH']
    B1L.LBSSMeLL = record['fu_LBSSMeLL']
    B1L.LBSSWeAt = record['fu_LBSSWeAT']
    B1L.LBStoLCD = record['fu_LBStoLCD']
    B1L.LBStoLHt = record['fu_LBStoHLt']
    B1L.LBSDBVIS = record['fu_LBSDBVIS']
    B1L.LBSCoNSt = record['fu_LBSCoNST']
    B1L.LBSHDStL = record['fu_LBSHDStL']
    B1L.LBSLSStL = record['fu_LBSLSStL']
    B1L.LBSUBLAD = record['fu_LBSUBLAD']
    B1L.LBSUStrM = record['fu_LBSUStrM']
    B1L.LBSUPASS = record['fu_LBSUPASS']
    B1L.LBSDZStU = record['fu_LBSDZStU']
    B1L.LBSDZStN = record['fu_LBSDZStN']
    B1L.LBSFAINt = record['fu_LBSFAINt']
    B1L.LBSPSyM  = record['fu_LBSPSyM']
    B1L.LBPSyAGe = record['fu_LBPSyAGe']
    B1L.LBSSUPSy = record['fu_LBSSUPSy']
    B1L.LBSSUPDI = record['fu_LBSSUPDI']
    B1L.LBSSUPHt = record['fu_LBSSUPHt']
    B1L.LBSStNSy = record['fu_LBSStNSy']
    B1L.LBSStNDI = record['fu_LBSStNDI']
    B1L.LBSStNHt = record['fu_LBSStNHt']
    B1L.LBSAGerM = record['fu_LBSAGerM']
    B1L.LBSAGeSM = record['fu_LBSAGeSM']
    B1L.LBSAGeGt = record['fu_LBSAGeGt']
    B1L.LBSAGeFL = record['fu_LBSAGeFL']
    B1L.LBSAGetr = record['fu_LBSAGetr']
    B1L.LBSAGeBr = record['fu_LBSAGeBr']
    B1L.LBSSCLAU = record['fu_LBSSCLAU']
    B1L.LBSSCLVr = record['fu_LBSSCLVr']
    B1L.LBSSCLot = record['fu_LBSSCLot']
    B1L.LBSSCor = record['Lfu_BSSCor']
    packet.append(B1L)

    B2L = lbd_fvp_forms.FormB2L()
    B2L.LBUDSPCH = record['fu_LBUDSPCH']
    B2L.LBUDSALV = record['fu_LBUDSALV']
    B2L.LBUDSWAL = record['fu_LBUDSWAL']
    B2L.LBUWrIte = record['fu_LBUWrIte']
    B2L.LBUDFooD = record['fu_LBUDFooD']
    B2L.LBUDreSS = record['fu_LBUDreSS']
    B2L.LBUDHyGN = record['fu_LBUDHyGN']
    B2L.LBUDtUrN = record['fu_LBUDtUrN']
    B2L.LBUDFALL = record['fu_LBUDFALL']
    B2L.LBUDFrZ  = record['fu_LBUDFrZ']
    B2L.LBUDWALK = record['fu_LBUDWALK']
    B2L.LBUDtreM = record['fu_LBUDtreM']
    B2L.LBUDSeNS = record['fu_LBUDSeNS']
    packet.append(B2L)

    B3L = lbd_fvp_forms.FormB3L()
    B3L.LBUMSPCH = record['fu_LBUMSPCH']
    B3L.LBUMSPCX = record['fu_LBUMSPCX']
    B3L.LBUMFACe = record['fu_LBUMFACe']
    B3L.LBUMFACX = record['fu_LBUMFACX']
    B3L.LBUMtrFA = record['fu_LBUMtrFA']
    B3L.LBUtrFAX = record['fu_LBUtrFAX']
    B3L.LBUMtrrH = record['fu_LBUMtrrH']
    B3L.LBUtrrHX = record['fu_LBUtrrHX']
    B3L.LBUMtrLH = record['fu_LBUMtrLH']
    B3L.LBUtrLHX = record['fu_LBUtrLHX']
    B3L.LBUMtrrF = record['fu_LBUMtrrF']
    B3L.LBUtrrFX = record['fu_LBUtrrFX']
    B3L.LBUMtrLF = record['fu_LBUMtrLF']
    B3L.LBUtrLFX = record['fu_LBUtrLFX']
    B3L.LBUMAtrH = record['fu_LBUMAtrH']
    B3L.LBUAtrHX = record['fu_LBUAtrHX']
    B3L.LBUMAtLH = record['fu_LBUMAtLH']
    B3L.LBUAtLHX = record['fu_LBUAtLHX']
    B3L.LBUMrGNK = record['fu_LBUMrGNK']
    B3L.LBUrGNKX = record['fu_LBUrGNKX']
    B3L.LBUMrGrU = record['fu_LBUMrGrU']
    B3L.LBUrGrUX = record['fu_LBUrGrUX']
    B3L.LBUMrGLU = record['fu_LBUMrGLU']
    B3L.LBUrGLUX = record['fu_LBUrGLUX']
    B3L.LBUMrGrL = record['fu_LBUMrGrL']
    B3L.LBUrGrLX = record['fu_LBUrGrLX']
    B3L.LBUMrGLL = record['fu_LBUMrGLL']
    B3L.LBUrGLLX = record['fu_LBUrGLLX']
    B3L.LBUMFtrH = record['fu_LBUMFtrH']
    B3L.LBUFtrHX = record['fu_LBUFtrHX']
    B3L.LBUMFtLH = record['fu_LBUMFtLH']
    B3L.LBUFtLHX = record['fu_LBUFtLHX']
    B3L.LBUMHMrH = record['fu_LBUMHMrH']
    B3L.LBUHMrHX = record['fu_LBUHMrHX']
    B3L.LBUMHMLH = record['fu_LBUMHMLH']
    B3L.LBUHMLHX = record['fu_LBUHMLHX']
    B3L.LBUMPSrH = record['fu_LBUMPSrH']
    B3L.LBUPSrHX = record['fu_LBUPSrHX']
    B3L.LBUMPSLH = record['fu_LBUMPSLH']
    B3L.LBUPSLHX = record['fu_LBUPSLHX']
    B3L.LBUMLGrL = record['fu_LBUMLGrL']
    B3L.LBULGrLX = record['fu_LBULGrLX']
    B3L.LBUMLGLL = record['fu_LBUMLGLL']
    B3L.LBULGLLX = record['fu_LBULGLLX']
    B3L.LBUMrISe = record['fu_LBUMrISe']
    B3L.LBUMrISX = record['fu_LBUMrISX']
    B3L.LBUMPoSt = record['fu_LBUMPoSt']
    B3L.LBUMPoSX = record['fu_LBUMPoSX']
    B3L.LBUMGAIt = record['fu_LBUMGAIt']
    B3L.LBUMGAIX = record['fu_LBUMGAIX']
    B3L.LBUPStBL = record['fu_LBUPStBL']
    B3L.LBUPStBX = record['fu_LBUPStBX']
    B3L.LBUMBrAD = record['fu_LBUMBrAD']
    B3L.LBUMBrAX = record['fu_LBUMBrAX']
    B3L.LBUMHNyr = record['fu_LBUMHNyr']
    B3L.LBUMHNyX = record['fu_LBUMHNyX']
    packet.append(B3L)

    B4L = lbd_fvp_forms.FormB4L()
    B4L.LBDeLUS  = record['fu_LBDeLUS']    
    B4L.LBDHUrt  = record['fu_LBDHUrt']    
    B4L.LBDSteAL = record['fu_LBDSteAL']
    B4L.LBDAFFr  = record['fu_LBDAFFr']    
    B4L.LBDGUeSt = record['fu_LBDGUeSt']
    B4L.LBDIMPoS = record['fu_LBDIMPoS']
    B4L.LBDHoMe  = record['fu_LBDHoMe']    
    B4L.LBDABAND = record['fu_LBDABAND']
    B4L.LBDPreS  = record['fu_LBDPreS']
    B4L.LBDotHer = record['fu_LBDotHer']
    B4L.LBDeLFrQ = record['fu_LBDeLFrQ']
    B4L.LBDeLSeV = record['fu_LBDeLSeV']
    B4L.LBDeLDSt = record['fu_LBDeLDSt']
    B4L.LBHALL   = record['fu_LBHALL']
    B4L.LBHVoICe = record['fu_LBHVoICe']
    B4L.LBHPeoPL = record['fu_LBHPeoPL']
    B4L.LBHNotPr = record['fu_LBHNotPr']
    B4L.LBHoDor  = record['fu_LBHoDor']
    B4L.LBHFeeL  = record['fu_LBHFeeL']
    B4L.LBHtASte = record['fu_LBHtASte']
    B4L.LBHotSeN = record['fu_LBHotSeN']
    B4L.LBHALFrQ = record['fu_LBHALFrQ']
    B4L.LBHALSeV = record['fu_LBHALSeV']
    B4L.LBHALDSt = record['fu_LBHALDSt']
    B4L.LBANXIet = record['fu_LBANXIet']
    B4L.LBANeVNt = record['fu_LBANeVNt']
    B4L.LBANreLX = record['fu_LBANreLX']
    B4L.LBANBrtH = record['fu_LBANBrtH']
    B4L.LBANBUtt = record['fu_LBANBUtt']
    B4L.LBANPLAC = record['fu_LBANPLAC']
    B4L.LBANSePr = record['fu_LBANSePr']
    B4L.LBANotHr = record['fu_LBANotHr']
    B4L.LBANXFrQ = record['fu_LBANXFrQ']
    B4L.LBANXSeV = record['fu_LBANXSeV']
    B4L.LBANXDSt = record['fu_LBANXDSt']
    B4L.LBAPAtHy = record['fu_LBAPAtHy']
    B4L.LBAPSPNt = record['fu_LBAPSPNt']
    B4L.LBAPCoNV = record['fu_LBAPCoNV']
    B4L.LBAPAFF  = record['fu_LBAPAFF']
    B4L.LBAPCHor = record['fu_LBAPCHor']
    B4L.LBAPINt  = record['fu_LBAPINt']
    B4L.LBAPFAML = record['fu_LBAPFAML']
    B4L.LBAPINtr = record['fu_LBAPINtr']
    B4L.LBAPotH  = record['fu_LBAPotH']
    B4L.LBAPAFrQ = record['fu_LBAPAFrQ']
    B4L.LBAPASeV = record['fu_LBAPASeV']
    B4L.LBAPADSt = record['fu_LBAPADSt']
    B4L.LBDoPAM  = record['fu_LBDoPAM']
    B4L.LBDAGe   = record['fu_LBDAGe']
    B4L.LBDDrUG1 = record['fu_LBDDrUG1']
    B4L.LBDDoSe1 = record['fu_LBDDoSe1']
    B4L.LBDAGe2  = record['fu_LBDAGe2']
    B4L.LBDDrUG2 = record['fu_LBDDrUG2']
    B4L.LBDDoSe2 = record['fu_LBDDoSe2']
    B4L.LBDeLAGe = record['fu_LBDeLAGe']
    B4L.LBDeLMeD = record['fu_LBDeLMeD']
    B4L.LBDeLMD1 = record['fu_LBDeLMD1']
    B4L.LBDeLMD2 = record['fu_LBDeLMD2']
    B4L.LBHALAGe = record['fu_LBHALAGe']
    B4L.LBHALMeD = record['fu_LBHALMeD']
    B4L.LBHALMD1 = record['fu_LBHALMD1']
    B4L.LBHALMD2 = record['fu_LBHALMD2']
    B4L.LBANXAGe = record['fu_LBANXAGe']
    B4L.LBANXMeD = record['fu_LBANXMeD']
    B4L.LBANXMD1 = record['fu_LBANXMD1']
    B4L.LBANXMD2 = record['fu_LBANXMD2']
    B4L.LBAPAAGe = record['fu_LBAPAAGe']
    B4L.LBAPAMeD = record['fu_LBAPAMeD']
    B4L.LBAPAMD1 = record['fu_LBAPAMD1']
    B4L.LBAPAMD2 = record['fu_LBAPAMD2']
    packet.append(B4L)

    B5L = lbd_fvp_forms.FormB5L()
    B5L.LBMLtHrG = record['fu_LBMLtHrG']
    B5L.LBMSLeeP = record['fu_LBMSLeeP']
    B5L.LBMDISrG = record['fu_LBMDISrG']
    B5L.LBMStAre = record['fu_LBMStAre']
    packet.append(B5L)

    B6L = lbd_fvp_forms.FormB6L()
    B6L.LBSPCGIM = record['fu_LBSPCGIM']
    B6L.LBSPDrM  = record['fu_LBSPDrM']
    B6L.LBSPyrS  = record['fu_LBSPyrS']
    B6L.LBSPMoS  = record['fu_LBSPMoS']
    B6L.LBSPINJS = record['fu_LBSPINJS']
    B6L.LBSPINJP = record['fu_LBSPINJP']
    B6L.LBSPCHAS = record['fu_LBSPCHAS']
    B6L.LBSPMoVe = record['fu_LBSPMoVe']
    B6L.LBSPLeGS = record['fu_LBSPLeGS']
    B6L.LBSPNerV = record['fu_LBSPNerv']
    B6L.LBSPUrGL = record['fu_LBSPUrGL']
    B6L.LBSPSeNS = record['fu_LBSPSeNS']
    B6L.LBSPWorS = record['fu_LBSPWorS']
    B6L.LBSPWALK = record['fu_LBSPWALK']
    B6L.LBSPAWAK = record['fu_LBSPAWAK']
    B6L.LBSPBrtH = record['fu_LBSPBrtH']
    B6L.LBSPtrt  = record['fu_LBSPtrt']
    B6L.LBSPCrMP = record['fu_LBSPCrMP']
    B6L.LBSPALrt = record['fu_LBSPALrt']
    packet.append(B6L)

    B7L = lbd_fvp_forms.FormB7L()
    B7L.LBSCLIV  = record['fu_LBSCLIV']    
    B7L.LBSCSLP  = record['fu_LBSCSLP']
    B7L.LBSCBeHV = record['fu_LBSCBeHV']
    B7L.LBSCDrM  = record['fu_LBSCDrM']
    B7L.LBSCyrS  = record['fu_LBSCyrS']
    B7L.LBSCMoS  = record['fu_LBSCMoS']
    B7L.LBSCINJS = record['fu_LBSCINJS']
    B7L.LBSCINJP = record['fu_LBSCINJP']
    B7L.LBSCCHAS = record['fu_LBSCCHAS']
    B7L.LBSCMoVe = record['fu_LBSCMoVe']
    B7L.LBSCLeGS = record['fu_LBSCLeGS']
    B7L.LBSCNerV = record['fu_LBSCNerV']
    B7L.LBSCSeNS = record['fu_LBSCSeNS']
    B7L.LBSCWorS = record['fu_LBSCWorS']
    B7L.LBSCWALK = record['fu_LBSCWALK']
    B7L.LBSCAWAK = record['fu_LBSCAWAK']
    B7L.LBSCBrtH = record['fu_LBSCBrtH']
    B7L.LBSCtrt  = record['fu_LBSCtrt']
    B7L.LBSCCrMP = record['fu_LBSCCrMP']
    B7L.LBSCALrt = record['fu_LBSCALrt']
    packet.append(B7L)

    B8L = lbd_fvp_forms.FormB8L()
    B8L.PACoGIMP = record['fu_PACoGIMP']
    B8L.PANSFALL = record['fu_PANSFALL']
    B8L.PANSWKoF = record['fu_PANSWKoF']
    B8L.PANSLyAW = record['fu_PANSLyAW']
    B8L.PANSWKer = record['fu_PANSWKer']
    B8L.PANSLttL = record['fu_PANSLttL']
    B8L.SCPArAte = record['fu_SCPArAte']
    B8L.PADSUNeX = record['fu_PADSUNeX']
    B8L.PADSSItP = record['fu_PADSSItP']
    B8L.PADSWAtV = record['fu_PADSWAtV']
    B8L.PADStALK = record['fu_PADStALK']
    B8L.PADSAWDy = record['fu_PADSAWDy']
    B8L.PADSFLDy = record['fu_PADSFLDy']
    packet.append(B8L)

    B9L = lbd_fvp_forms.FormB9L()
    B9L.CoNSFALL = record['fu_CoNSFALL']
    B9L.CoNSWKoF = record['fu_CoNSWKoF']
    B9L.CoNSLyAW = record['fu_CoNSLyAW']
    B9L.CoNSWKer = record['fu_CoNSWKer']
    B9L.CoNSLttL = record['fu_CoNSLttL']
    B9L.SCCorAte = record['fu_SCCorAte']
    B9L.CoDSUNeX = record['fu_CoDSUNeX']
    B9L.CoDSSItP = record['fu_CoDSSItP']
    B9L.CoDSWAtV = record['fu_CoDSWAtV']
    B9L.CoDStALK = record['fu_CoDStALK']
    B9L.CoDSAWDy = record['fu_CoDSAWDy']
    B9L.CoDSFLDy = record['fu_CoDSFLDy']
    B9L.SCCoFrSt = record['fu_SCCoFrSt']
    B9L.SCCoAGeN = record['fu_SCCoAGeN']
    B9L.SCCoAGeD = record['fu_SCCoAGeD']
    B9L.SCCoCoMP = record['fu_SCCoCoMP']
    B9L.SCCoSCVr = record['fu_SCCoSCVr']
    B9L.SCCootH  = record['fu_SCCootH']
    B9L.SCCoSCor = record['fu_SCCoSCor']
    packet.append(B9L)

    C1L = lbd_fvp_forms.FormC1L()
    C1L.LBNSWorD = record['fu_LBNSWorD']
    C1L.LBNSCoLr = record['fu_LBNSCoLr']
    C1L.LBNSCLWD = record['fu_LBNSCLWD']
    C1L.LBNPFACe = record['fu_LBNPFACe']
    C1L.LBNPNoIS = record['fu_LBNPNoIS']
    C1L.LBNPtCor = record['fu_LBNPtCor']
    C1L.LBNPPArD = record['fu_LBNPPArD']
    packet.append(C1L)

    D1L = lbd_fvp_forms.FormD1L()
    D1L.LBCDSCoG = record['fu_LBCDSCoG']
    D1L.LBCCMeM  = record['fu_LBCCMeM']
    D1L.LBCCLANG = record['fu_LBCCLANG']
    D1L.LBCCAtt  = record['fu_LBCCAtt']
    D1L.LBCCeXDe = record['fu_LBCCeXDe']
    D1L.LBCCVIS  = record['fu_LBCCVIS']
    D1L.LBCDSMoV = record['fu_LBCDSMoV']
    D1L.LBCMBrAD = record['fu_LBCMBrAD']
    D1L.LBCMrIGD = record['fu_LBCMrIGD']
    D1L.LBCMrtrM = record['fu_LBCMrtrM']
    D1L.LBCMPtrM = record['fu_LBCMPtrM']
    D1L.LBCMAtrM = record['fu_LBCMAtrM']
    D1L.LBCMMyoC = record['fu_LBCMMyoC']
    D1L.LBCMGAIt = record['fu_LBCMGAIt']
    D1L.LBCMPINS = record['fu_LBCMPINS']
    D1L.LBCDSBeV = record['fu_LBCDSBeV']
    D1L.LBCBDeP  = record['fu_LBCBDeP']
    D1L.LBCBAPA  = record['fu_LBCBAPA']
    D1L.LBCBANX  = record['fu_LBCBANX']
    D1L.LBCBHALL = record['fu_LBCBHALL']
    D1L.LBCBDeL  = record['fu_LBCBDeL'] 
    D1L.LBCDSAUt = record['fu_LBCDSAUt']
    D1L.LBCAreM  = record['fu_LBCAreM']
    D1L.LBCAAPN  = record['fu_LBCAAPN']
    D1L.LBCALGSL = record['fu_LBCALGSL']
    D1L.LBCArSLe = record['fu_LBCArSLe']
    D1L.LBCADtSL = record['fu_LBCADtSL']
    D1L.LBCACGFL = record['fu_LBCACGFL']
    D1L.LBCAHyPt = record['fu_LBCAHyPt']
    D1L.LBCACoNS = record['fu_LBCACoNS']
    D1L.LBCAHyPS = record['fu_LBCAHyPS']
    D1L.LBCAFALL = record['fu_LBCAFALL']
    D1L.LBCASyNC = record['fu_LBCASyNC']
    D1L.LBCASNAP = record['fu_LBCASNAP']
    D1L.LBCoGSt  = record['fu_LBCoGSt']
    D1L.LBCoGDX  = record['fu_LBCoGDX']
    packet.append(D1L)
    
    E1L = lbd_fvp_forms.FormE1L()
    E1L.LBGNeWGN = record['fu_LBGNeWGN']
    E1L.LBGLrrK2 = record['fu_LBGLrrK2']
    E1L.LBGLrKiS = record['fu_LBGPrKiS']
    E1L.LBGPArK2 = record['fu_LBGPArK2']
    E1L.LBGPK2iS = record['fu_LBGPK2iS']
    E1L.LBGPArK7 = record['fu_LBGPArK7']
    E1L.LBGPK7iS = record['fu_LBGPK7iS']
    E1L.LBGPiNK1 = record['fu_LBGPiNK1']
    E1L.LBGPNKiS = record['fu_LBGPNKiS']
    E1L.LBGSNCA  = record['fu_LBGSNCA']
    E1L.LBGSNCiS = record['fu_LBGSNCiS']
    E1L.LBGGBA   = record['fu_LBGGBA']
    E1L.LBGGBAiS = record['fu_LBGGBAiS']
    E1L.LBGotHr  = record['fu_LBGotHr']
    E1L.LBGotHiS = record['fu_LBGotHiS']
    E1L.LBGotHX  = record['fu_LBGotHX']
    packet.append(E1L)

    E2L = lbd_fvp_forms.FormE2L()
    E2L.LBISMrI  = record['fu_LBISMrI']    
    E2L.LBISMMo  = record['fu_LBISMMo']
    E2L.LBISMDy  = record['fu_LBISMDy']
    E2L.LBISMyr  = record['fu_LBISMyr']
    E2L.LBISMQAV = record['fu_LBISMQAV']
    E2L.LBISMHIP = record['fu_LBISMHIP']
    E2L.LBISMAVL = record['fu_LBISMAVL']
    E2L.LBISMDCM = record['fu_LBISMDCM']
    E2L.LBISMFMt = record['fu_LBISMFMt']
    E2L.LBISMADN = record['fu_LBISMADN']
    E2L.LBISMVer = record['fu_LBISMVer']
    E2L.LBISMMAN = record['fu_LBISMMAN']
    E2L.LBISMoM  = record['fu_LBISMoM']
    E2L.LBISMStr = record['fu_LBISMStr']
    E2L.LBISMoS  = record['fu_LBISMoS']
    E2L.LBIFPet  = record['fu_LBIFPet']
    E2L.LBIFPMo  = record['fu_LBIFPMo']
    E2L.LBIFPDy  = record['fu_LBIFPDy']
    E2L.LBIFPyr  = record['fu_LBIFPyr']
    E2L.LBIFPQAV = record['fu_LBIFPQAV']
    E2L.LBIFPoCC = record['fu_LBIFPoCC']
    E2L.LBIFPtPP = record['fu_LBIFPtPP']
    E2L.LBIFPISL = record['fu_LBIFPISL']
    E2L.LBIFPAVL = record['fu_LBIFPAVL']
    E2L.LBIFPDCM = record['fu_LBIFPDCM']
    E2L.LBIFPFMt = record['fu_LBIFPFMt']
    E2L.LBIFPADN = record['fu_LBIFPADN']
    E2L.LBIFPVer = record['fu_LBIFPVer']
    E2L.LBIFPMAN = record['fu_LBIFPMAN']
    E2L.LBIFPoM  = record['fu_LBIFPoM']
    E2L.LBIAPet  = record['fu_LBIAPet']
    E2L.LBIAPMo  = record['fu_LBIAPMo']
    E2L.LBIAPDy  = record['fu_LBIAPDy']
    E2L.LBIAPyr  = record['fu_LBIAPyr']
    E2L.LBIAPQAV = record['fu_LBIAPQAV']
    E2L.LBIAPAVL = record['fu_LBIAPAVL']
    E2L.LBIAPDCM = record['fu_LBIAPDCM']
    E2L.LBIAPFMt = record['fu_LBIAPFMt']
    E2L.LBIAPLIG = record['fu_LBIAPLIG']
    E2L.LBIAPoL  = record['fu_LBIAPoL']
    E2L.LBIAPADN = record['fu_LBIAPADN']
    E2L.LBIAPVer = record['fu_LBIAPVer']
    E2L.LBIAPMAN = record['fu_LBIAPMAN']
    E2L.LBIAPoM  = record['fu_LBIAPoM']
    E2L.LBItPet  = record['fu_LBItPet']
    E2L.LBItPMo  = record['fu_LBItPMo']
    E2L.LBItPDy  = record['fu_LBItPDy']
    E2L.LBItPyr  = record['fu_LBItPyr']
    E2L.LBItPQAV = record['fu_LBItPQAV']
    E2L.LBItPAVL = record['fu_LBItPAVL']
    E2L.LBItPDCM = record['fu_LBItPDCM']
    E2L.LBItPFMt = record['fu_LBItPFMt']
    E2L.LBItPLIG = record['fu_LBItPLIG']
    E2L.LBItPoL  = record['fu_LBItPoL']
    E2L.LBItPADN = record['fu_LBItPADN']
    E2L.LBItPVer = record['fu_LBItPVer']
    E2L.LBItPMAN = record['fu_LBItPMAN']
    E2L.LBItPoM  = record['fu_LBItPoM']
    E2L.LBIDAtS  = record['fu_LBIDAtS']
    E2L.LBIDSMo  = record['fu_LBIDSMo']
    E2L.LBIDSDy  = record['fu_LBIDSDy']
    E2L.LBIDSyr  = record['fu_LBIDSyr']
    E2L.LBIDSQAV = record['fu_LBIDSQAV']
    E2L.LBIDSABN = record['fu_LBIDSABN']
    packet.append(E2L)

    E3L = lbd_fvp_forms.FormE3L()
    E3L.LBoPoLyS = record['fu_LBoPoLyS']
    E3L.LBoPoSMo = record['fu_LBoPoSMo']
    E3L.LBoPoSDy = record['fu_LBoPoSDy']
    E3L.LBoPoSyr = record['fu_LBoPoSyr']
    E3L.LBoPoPoS = record['fu_LBoPoPoS']
    E3L.LBoPoAVL = record['fu_LBoPoAVL']
    E3L.LBoCMIBG = record['fu_LBoCMIBG']
    E3L.LBoCMMo  = record['fu_LBoCMMo']
    E3L.LBoCMDy  = record['fu_LBoCMDy']
    E3L.LBoCMyr  = record['fu_LBoCMyr']
    E3L.LBoCMPoS = record['fu_LBoCMPoS']
    E3L.LBoCMAVL = record['fu_LBoCMAVL']
    E3L.LBoANoS  = record['fu_LBoANoS']
    E3L.LBoANMo  = record['fu_LBoANMo']
    E3L.LBoANDy  = record['fu_LBoANDy']
    E3L.LBoANyr  = record['fu_LBoANyr']
    E3L.LBoANPoS = record['fu_LBoANPoS']
    E3L.LBoANAVL = record['fu_LBoANAVL']
    E3L.LBoANVer = record['fu_LBoANVer']
    E3L.LBoANotH = record['fu_LBoANotH']
    E3L.LBoeeG   = record['fu_LBOeeG']
    E3L.LBoeGMo  = record['fu_LBoeGMo']
    E3L.LBoeGDy  = record['fu_LBoeGDy']
    E3L.LBoeGyr  = record['fu_LBoeGyr']
    E3L.LBoeGPoS = record['fu_LBoeGPoS']
    E3L.LBoeGAVL = record['fu_LBoeGAVL']
    E3L.LBoMSLt  = record['fu_LBoMSLt']
    E3L.LBoMSMo  = record['fu_LBoMSMo']
    E3L.LBoMSDy  = record['fu_LBoMSDy']
    E3L.LBoMSyr  = record['fu_LBoMSyr']
    E3L.LBoMSPoS = record['fu_LBoMSPoS']
    E3L.LBoMSAVL = record['fu_LBoMSAVL']
    E3L.LBotILt  = record['fu_LBotILt']
    E3L.LBotLMo  = record['fu_LBotLMo']
    E3L.LBotLDy  = record['fu_LBotLDY']
    E3L.LBotLyr  = record['fu_LBotLyr']
    E3L.LBotLPoS = record['fu_LBoPoS']
    E3L.LBotLAVL = record['fu_LBoAVL']
    E3L.LBoQSArt = record['fu_LBoQSArt']
    E3L.LBoQSMo  = record['fu_LBoQSMo']
    E3L.LBoQSDy  = record['fu_LBoQSDy']
    E3L.LBoQSyr  = record['fu_LBoQSyr']
    E3L.LBoQSPoS = record['fu_LBoQSPoS']
    E3L.LBoSGAVL = record['fu_LBoSGAVL']
    E3L.LBotHerM = record['fu_LBotHerM']
    E3L.LBotHMo  = record['fu_LBotHMo']
    E3L.LBotHDy  = record['fu_LBotHDy']
    E3L.LBotHyr  = record['fu_LBotHyr']
    E3L.LBotHPoS = record['fu_LBotHPoS']
    E3L.LBotHAVL = record['fu_LBotHAVL']
    E3L.LBoCGAIt = record['fu_LBoCGAIt']
    E3L.LBoCGMo  = record['fu_LBoCGMo']
    E3L.LBoCGDy  = record['fu_LBoCGDy']
    E3L.LBoCGyr  = record['fu_LBoCGyr']
    E3L.LBoCGPoS = record['fu_LBoCGPoS']
    E3L.LBoCGAVL = record['fu_LBoCGAVL']
    packet.append(E3L)

    update_header(record,packet)
    return packet

# update_header takes the header form to fill out info about the full packet, 
# but i'm not sure what this if/else thing does

def update_header(record, packet):
    for header in packet:
        header.PACKET = "I"
        header.FORMID = header.form_name
        if header.FORMID.value == "B5 ":
            header.FORMVER = "3.1"
        elif header.FORMID.value == "C1S":
            header.FORMVER = 2
        else:
            header.FORMVER = 3
        header.ADCID = record['adcid']
        header.PTID = record['ptid']
        header.VISITMO = record['visitmo']
        header.VISITDAY = record['visitday']
        header.VISITYR = record['visityr']
        header.VISITNUM = record['visitnum']
        header.INITIALS = record['initials']
