version: '3.1'

services:
  db:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_DATABASE: log_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 4000:3306
    volumes:
      - ./schema:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
